### ISSUE TITLE
Python part 3  - materials missing

### ISSUE THREAD

**Issue by juliogomez** [CiscoDevNet/netprog_basics#20]
In the netprog_basics repo, under ‘programming fundamentals’ - ‘python_part_3’, it is a little bit confusing… In the video you are using interactive python for the libraries demos, but the commands are not included in the repo… In fact the repo includes commands in a scratchpad file, but those go against 127.0.0.1 (so I guess you were using vagrant when you wrote it). Overall it is confusing, feels like the repo is a little bit “disconnected’ from the video.

**Comment by ChileFlake** [comment]
Did you find a way to solve this ?

**Comment by hpreston** [comment]
The scratchpad file has been removed in a pending code update, and there are now Python files that match the video examples.
