### ISSUE TITLE
Programming Fundamentals Rest-part1 curl examples #3 error 406

### ISSUE THREAD

**Issue by MaVirginiaGZ** [CiscoDevNet/netprog_basics#23]
When you run the code from the example #3 in the curl examples from this path:
programming_fundamentals/rest_part_1/curl_examples.sh

You get error code 406  because the command accepts 'application/yang-data+json' and the host is only sending in 'application/yang-data+xml' (as of today 06/12/2019)

So you need to change the command to: -H 'accept: application/yang-data+xml' \

**Comment by hpreston** [comment]
This has been tested and the example with JSON is working now. Thanks for raising.
