### ISSUE TITLE
Sandbox working?

### ISSUE THREAD

**Issue by eggee** [CiscoDevNet/netprog_basics#24]
Can someone verify this Lab/Sanbox is functional:
NETCONF/YANG & RESTCONF on IOS XE 
The Sandbox opens, but the Connections Host URL doesn't work for me:

Access Details:
Developers and network engineers access the "NETCONF/YANG and RESTCONF on IOS XE" Always On Sandbox directly using the following information:

CSR1000V Host : ios-xe-mgmt.cisco.com
SSH Port: 8181
NETCONF Port: 10000
RESTCONF Port : 9443 (HTTPS)

**Comment by hpreston** [comment]
You may have had a case where the Sandbox was having issues momentarily, but it is a functioning Sandbox and used in many examples.
