### ISSUE TITLE
Did anyone manage to run example 3 by netconf ?

### ISSUE THREAD

**Issue by toxkalcan** [CiscoDevNet/netprog_basics#32]
When you run the code from the example #3 in the curl examples from this path:
programming_fundamentals/rest_part_1/curl_examples.sh

if we change the header to netconf , it does not work

 curl -vk   -u developer:C1sco12345   -H 'accept: application/yang-data+json'   http://ios-xe-mgmt.cisco.com:10000/netconf-yang/data/ietf-interfaces:interfaces/interface=GigabitEthernet1

* Server auth using Basic with user 'developer'
> GET /netconf-yang/data/ietf-interfaces:interfaces/interface=GigabitEthernet1 HTTP/1.1
> Authorization: Basic ZGV2ZWxvcGVyOkMxc2NvMTIzNDU=
> User-Agent: curl/7.29.0
> Host: ios-xe-mgmt.cisco.com:10000
> accept: application/yang-data+json
> 
SSH-2.0-OpenSSH_6.1
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer

Does anyone know why ?

**Comment by hpreston** [comment]
NETCONF runs over SSH for transport, not HTTPS.  To use NETCONF you'd connect in a very different way. This topic is covered in the NETCONF lesson in the videos.
