### ISSUE TITLE
sandboxdnac2 is not authenticating

### ISSUE THREAD

**Issue by toxkalcan** [CiscoDevNet/netprog_basics#40]
at the videos credentials are given as 
devnetuser
Cisco123! , however this does not work . I believe sandboxdnac2 somehow has been decommissioned ?

**Comment by hpreston** [comment]
This may have been a transient issue when you tested.  SandboxDNAC2 is alive and working still, but does undergo occasional maintenance.

**Comment by nomagean** [comment]
Hi Hank.
Happy new year!!All ticket closures are coming to our inboxes. 
Kind RegardsNomsa Mwayenga 

    On Thursday, 14 January 2021, 21:22:55 GMT+2, Hank Preston <notifications@github.com> wrote:  
 
 


Closed #40.
