### ISSUE TITLE
Python Part 3 request.get Access Denied Why ?

### ISSUE THREAD

**Issue by lowfell** [CiscoDevNet/netprog_basics#49]
In lesson in Python Part3 trying to use the request.get

Now the lesson says to leverage the devnet sandbox then it gives you a link, which i go to and use the vpn. i run the query and then i get the errors "access-denied" for protocol?

Now in the video he uses 10.10.20.21 however in the info for the lesson it say to reference the always on sandbox. The router there has an ip address of 10.10.20.48 so this is the ip address I've used. so i enter all the correct info and get the cert warning, which i expect, but when I run the print command to get the interface info I'm getting errors for access denied and protocol, why is this ?  Is it to do with the headers I' using in my request?

I'm going to have a rant here. Cisco are encouraging people to learn this stuff and the devnet box isn't setup properly so I'm getting the wrong reply when i add the query. what's the point if the info you're giving us is wrong? apologies but i'm very frustrated!

Firstly you can see i make it as far as the router as i get a cert warning regarding the self certs

router = {“ip”: “10.10.20.48” ,
… “port”:“443”,
… “user”:“root”,
… “pass”:“cisco123”}

headers = {“Accept”: “application/yang-data+json”}
u = “https://{}:{}/restconf/data/interfaces/interface=Gigabitethernet1”
u = u.format(router[“ip”], router[“port”])
print(u)
https://10.10.20.48:443/restconf/data/interfaces/interface=Gigabitethernet1

r = requests.get(u,
… headers = headers,
… auth=(router[“user”], router[“pass”]),
… verify=False)
C:\Users\M7551873\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host ‘10.10.20.48’.
Adding certificate verification is strongly advised. See: Advanced Usage - urllib3 2.0.0.dev0 documentation

I then run pprint and expect it to return the interface information but i get access denied. I expect this is because I’m being given the wrong credentials? Or is it the request headers? this is what i get when running the print command

pprint(r.text)
Traceback (most recent call last):
File “”, line 1, in
NameError: name ‘pprint’ is not defined

from pprint import pprint
pprint(r.text)
(’{\n’
’ “errors”: {\n’
’ “error”: [\n’
’ {\n’
’ “error-tag”: “access-denied”,\n’
’ “error-type”: “protocol”\n’
’ }\n’
’ ]\n’
’ }\n’
‘}\n’)

print(r.text)
{
“errors”: {
“error”: [
{
“error-tag”: “access-denied”,
“error-type”: “protocol”
}
]
}
}

As far as i can see the router is running restconf?
csr1000v-1#sho run
Building configuration...

Current configuration : 4209 bytes
!
! Last configuration change at 18:04:57 UTC Sat Jan 9 2021 by developer
!
version 16.9
service timestamps debug datetime msec
service timestamps log datetime msec
platform qfp utilization monitor load 80
no platform punt-keepalive disable-kernel-core
platform console virtual
!
hostname csr1000v-1
!
boot-start-marker
boot-end-marker
!
!
no logging console
enable secret 5 $1$20ue$uC.uSGo6nvfWs63EjjzRP.
!
no aaa new-model
!
!
!
!
!
!
!
ip domain name abc.inc
!
!
!
login on-success log
!
!
!
!
!
!
!
subscriber templating
!
!
!
!
!
multilink bundle-name authenticated
!
!
!
!
!
crypto pki trustpoint TP-self-signed-65385644
enrollment selfsigned
subject-name cn=IOS-Self-Signed-Certificate-65385644
revocation-check none
rsakeypair TP-self-signed-65385644
!
!
crypto pki certificate chain TP-self-signed-65385644
certificate self-signed 01
3082032C 30820214 A0030201 02020101 300D0609 2A864886 F70D0101 05050030
2F312D30 2B060355 04031324 494F532D 53656C66 2D536967 6E65642D 43657274
69666963 6174652D 36353338 35363434 301E170D 31393035 32323139 33383539
5A170D33 30303130 31303030 3030305A 302F312D 302B0603 55040313 24494F53
2D53656C 662D5369 676E6564 2D436572 74696669 63617465 2D363533 38353634
34308201 22300D06 092A8648 86F70D01 01010500 0382010F 00308201 0A028201
0100C96F D53A4C23 F96F71E2 BA91DAA3 C4546EAD 399F1B32 CA9BB364 C528FFFD
9F2A0CCE D5FD2756 6452B91B 2DCC328D 6951AEF3 BD25A687 62354EF7 0C68717E
94BF7B1E 320231A5 FFB9B765 A5616FD3 673709D5 7E89DB6D E6A14B85 E3FE2153
DFA8B852 BB37CCB4 4C523450 2A757DB5 8FB13133 0DE79EAE 579DDFE9 EA4B6C2A
CD8DC33E F69A0F45 020367D1 0C8451F1 AB9C0891 2A1AF1E5 2245E739 43CB1F48
03324EDF 7A647E25 86552D27 EEE5E05D EB01D886 4D00C47A B9B022AD AACA9E84
5D5627BD B0D6F2FC C5103F0E 808E5822 86B63301 C2B7B50C BBA6F3D1 471F2A53
B02E5DA1 DC1ECF46 116EAC77 160090AF 7AB23919 1896AA07 6893E638 8CE05F53
E5EB0203 010001A3 53305130 0F060355 1D130101 FF040530 030101FF 301F0603
551D2304 18301680 14A162A4 D3CD7E6B 7E775D4E CA02E2DA 5AEBC668 45301D06
03551D0E 04160414 A162A4D3 CD7E6B7E 775D4ECA 02E2DA5A EBC66845 300D0609
2A864886 F70D0101 05050003 82010100 8034A615 EED522BA 8A4D45D9 107A1C72
B622ECB6 26EB96AA AD26A14D 34FC54B6 93F03F5D F1C1F1DB C716B213 67342ADF
0E4F4313 00C19914 B8EAD89F D90FDCF7 943D9304 3E3158A7 2E7558D3 C90D9540
F8CDB4AE 9A266418 DA396402 6954BAA6 D49FB91B 5795EBD7 17C260BA AD2DCD40
6C86E58F 3D521061 A7ADC34D B1875BBA A5EC9877 57D65870 1134D226 EA884C43
CEA1F154 905F1872 E5FA575F 9C060B34 BA18FBB5 E03AB440 12D37659 B70A7C8A
9D32DD93 95BBE653 F39D1A30 2062C41C B3857FA5 9C6E2FAE 61E10F20 7B8994B9
DADCE497 38BD1450 8D1BF507 E9C0CD94 EFED9FA2 D888C58F 700A7182 1A2F12B2
32AF600E 7623C1E2 026B06FA EA75E800
quit
!
!
!
!
!
!
!
!
license udi pid CSR1000V sn 9CO9QHEWZEL
license boot level ax
no license smart enable
diagnostic bootup level minimal
!
spanning-tree extend system-id
!
netconf-yang
!
restconf
!
username developer privilege 15 secret 5 $1$apX9$osH3JUIsEok.XVu5bKG0D0
username cisco privilege 15 secret 5 $1$3PeY$CBmJ7lqSYLpLn6uImSoMD0
username root privilege 15 secret 5 $1$F2Ov$Ax5.47hkCDThKbWt1.M4U0
!
redundancy
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
interface GigabitEthernet1
description MANAGEMENT INTERFACE - DON'T TOUCH ME
ip address 10.10.20.48 255.255.255.0
negotiation auto
no mop enabled
no mop sysid
!
interface GigabitEthernet2
description Network Interface
no ip address
shutdown
negotiation auto
no mop enabled
no mop sysid
!
interface GigabitEthernet3
description Network Interface
no ip address
shutdown
negotiation auto
no mop enabled
no mop sysid
!
ip forward-protocol nd
ip http server
ip http authentication local
ip http secure-server
ip route 0.0.0.0 0.0.0.0 GigabitEthernet1 10.10.20.254
!
ip ssh rsa keypair-name ssh-key
ip ssh version 2
ip scp server enable
!
!
!
!
!
control-plane

csr1000v-1#show platform software yang-management process monitor
COMMAND PID S VSZ RSS %CPU %MEM ELAPSED
confd 24825 S 833180 138792 0.2 1.7 01:24:29
confd-startup.s 24612 S 19692 4388 0.0 0.0 01:24:30
dmiauthd 25649 S 282420 27360 0.0 0.3 01:24:27
ncsshd 25981 S 169304 10396 0.0 0.1 01:24:25
ncsshd_bp 25871 S 175024 10560 0.0 0.1 01:24:26
ndbmand 25430 S 599624 71432 0.0 0.8 01:24:27
nesd 25173 S 192704 14592 0.0 0.1 01:24:28
nginx 26230 S 338612 19700 0.0 0.2 01:24:15
nginx 26237 S 344668 17928 0.0 0.2 01:23:45
pubd 24381 S 657128 73504 0.0 0.9 01:24:31
syncfd 24943 S 193624 19212 0.0 0.2 01:24:29

c

**Comment by annegentle** [comment]
Hiya @lowfell  -- you're definitely onto the right reason for the error, it is the credentials. 

Run the code at https://github.com/CiscoDevNet/netprog_basics/blob/master/programming_fundamentals/python_part_3/api_requests_example.py -- it is using the latest `10.10.20.48` IP address value, and the credentials work. You likely need to recheck the credentials that you are using locally. The DevNet Sandbox no longer uses `root` for user names. The video can't be updated at this point, but the code is accurate.

When running the example in this repo you should see: (The ssl warning is expected.)
```
$ python api_requests_example.py
/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.10.20.48'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
('{\n'
 '  "Cisco-IOS-XE-interfaces-oper:interface": {\n'
 '    "name": "GigabitEthernet1",\n'
 '    "interface-type": "iana-iftype-ethernet-csmacd",\n'
 '    "admin-status": "if-state-up",\n'
 '    "oper-status": "if-oper-state-ready",\n'
 '    "last-change": "2021-01-10T19:07:30.000037+00:00",\n'
 '    "if-index": 1,\n'
 '    "phys-address": "00:50:56:bf:e2:e7",\n'
 '    "speed": "1024000000",\n'
 '    "statistics": {\n'
 '      "discontinuity-time": "2021-01-10T19:05:48.000356+00:00",\n'
 '      "in-octets": "487353",\n'
 '      "in-unicast-pkts": "4818",\n'
 '      "in-broadcast-pkts": "0",\n'
 '      "in-multicast-pkts": "0",\n'
 '      "in-discards": 0,\n'
 '      "in-errors": 0,\n'
 '      "in-unknown-protos": 0,\n'
 '      "out-octets": 88090,\n'
 '      "out-unicast-pkts": "214",\n'
 '      "out-broadcast-pkts": "0",\n'
 '      "out-multicast-pkts": "0",\n'
 '      "out-discards": "0",\n'
 '      "out-errors": "0",\n'
 '      "rx-pps": "0",\n'
 '      "rx-kbps": "0",\n'
 '      "tx-pps": "0",\n'
 '      "tx-kbps": "0",\n'
 '      "num-flaps": "0",\n'
 '      "in-crc-errors": "0"\n'
 '    },\n'
 '    "vrf": "",\n'
 '    "ipv4": "10.10.20.48",\n'
 '    "ipv4-subnet-mask": "255.255.255.0",\n'
 '    "description": "MANAGEMENT INTERFACE - DON\'T TOUCH ME",\n'
 '    "mtu": 1500,\n'
 '    "input-security-acl": "",\n'
 '    "output-security-acl": "",\n'
 '    "v4-protocol-stats": {\n'
 '      "in-pkts": "112",\n'
 '      "in-octets": "14119",\n'
 '      "in-error-pkts": "0",\n'
 '      "in-forwarded-pkts": "0",\n'
 '      "in-forwarded-octets": "0",\n'
 '      "in-discarded-pkts": "0",\n'
 '      "out-pkts": "209",\n'
 '      "out-octets": "87790",\n'
 '      "out-error-pkts": "0",\n'
 '      "out-forwarded-pkts": "209",\n'
 '      "out-forwarded-octets": "0",\n'
 '      "out-discarded-pkts": "0"\n'
 '    },\n'
 '    "v6-protocol-stats": {\n'
 '      "in-pkts": "0",\n'
 '      "in-octets": "0",\n'
 '      "in-error-pkts": "0",\n'
 '      "in-forwarded-pkts": "0",\n'
 '      "in-forwarded-octets": "0",\n'
 '      "in-discarded-pkts": "0",\n'
 '      "out-pkts": "0",\n'
 '      "out-octets": "0",\n'
 '      "out-error-pkts": "0",\n'
 '      "out-forwarded-pkts": "0",\n'
 '      "out-forwarded-octets": "0",\n'
 '      "out-discarded-pkts": "0"\n'
 '    },\n'
 '    "bia-address": "00:50:56:bf:e2:e7",\n'
 '    "ipv4-tcp-adjust-mss": 0,\n'
 '    "ipv6-tcp-adjust-mss": 0,\n'
 '    "ether-state": {\n'
 '      "negotiated-duplex-mode": "auto-duplex",\n'
 '      "negotiated-port-speed": "speed-unknown",\n'
 '      "auto-negotiate": true,\n'
 '      "enable-flow-control": false\n'
 '    },\n'
 '    "ether-stats": {\n'
 '      "in-mac-control-frames": "0",\n'
 '      "in-mac-pause-frames": "0",\n'
 '      "in-oversize-frames": "0",\n'
 '      "in-jabber-frames": "0",\n'
 '      "in-fragment-frames": "0",\n'
 '      "in-8021q-frames": "0",\n'
 '      "out-mac-control-frames": "0",\n'
 '      "out-mac-pause-frames": "0",\n'
 '      "out-8021q-frames": "0"\n'
 '    }\n'
 '  }\n'
 '}\n')
```

**Comment by lowfell** [comment]
Hello and thanks again. The username root is still a username on the router also the MOTD banner states that NETCONF and RESTCONF are enabled Please see the output here.

Welcome to the DevNet Sandbox for CSR1000v and IOS XE

The following programmability features are already enabled:
  - NETCONF
  - RESTCONF

Thanks for stopping by.



csr1000v-1#sho run | include username
username developer privilege 15 secret 5 $1$apX9$osH3JUIsEok.XVu5bKG0D0
username cisco privilege 15 secret 5 $1$3PeY$CBmJ7lqSYLpLn6uImSoMD0
username root privilege 15 secret 5 $1$F2Ov$Ax5.47hkCDThKbWt1.M4U0
csr1000v-1#



I did actually get it to work using the "developer" credentials. I've actually learned more from it NOT working than working so that's actually a plus.
 
 So. for future reference seeing as the videos can't be updated I should be referring to the instructions here as they will be up to date, yes?

Sorry again for being a pain,
Brian
