### ISSUE TITLE
Missing command files

### ISSUE THREAD

**Issue by juliogomez** [CiscoDevNet/netprog_basics#6]
The folder for 'Programming Fundamentals' - 'Python part 3' (https://github.com/CiscoDevNet/netprog_basics/tree/master/programming_fundamentals/python_part_3) does not include the command files for the first section on 'Libraries to work with data'. 

It would be great to include those files so that readers do not have to type every command (prone to typing error).

**Comment by hpreston** [comment]
Good idea.  It's been added.
